name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y gcc curl pkg-config libssl-dev make

      - name: Generate documentation
        run: |
          pip install uv && uv sync --extra dev
          source .venv/bin/activate && make docs

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy documentation
        id: deployment
        uses: actions/deploy-pages@v4
